### ISSUE TITLE
it is better to use [skip version] instead of [ignore]

### ISSUE THREAD

**Issue by vbilici** [brcnblc/ci-auto-version#3]
I think it make more sense if I could see something like [skip version] instead of [ignore] in the commit message

**Comment by brcnblc** [comment]
--ignore-pattern, -gp Definition : Defines commit message pattern to bypass version upgrade. Default Value : [ignore]

You may call program with --ignore-pattern "[skip version]" or -gp "[skip version]" to change ignore pattern.
